# Generated by Django 5.2 on 2025-07-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_contact_delete_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dep_description',
        ),
        migrations.AddField(
            model_name='contact',
            name='dep_phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
